/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class keyboard_KeyPressReader */

#ifndef _Included_keyboard_KeyPressReader
#define _Included_keyboard_KeyPressReader
#ifdef __cplusplus
extern "C" {
#endif
#undef keyboard_KeyPressReader_ARROW_UP
#define keyboard_KeyPressReader_ARROW_UP 1001L
#undef keyboard_KeyPressReader_ARROW_DOWN
#define keyboard_KeyPressReader_ARROW_DOWN 1002L
#undef keyboard_KeyPressReader_ARROW_LEFT
#define keyboard_KeyPressReader_ARROW_LEFT 1003L
#undef keyboard_KeyPressReader_ARROW_RIGHT
#define keyboard_KeyPressReader_ARROW_RIGHT 1004L
#undef keyboard_KeyPressReader_BACKSPACE
#define keyboard_KeyPressReader_BACKSPACE 127L
#undef keyboard_KeyPressReader_SPACE
#define keyboard_KeyPressReader_SPACE 32L
#undef keyboard_KeyPressReader_INTRO
#define keyboard_KeyPressReader_INTRO 10L
#undef keyboard_KeyPressReader_TAB
#define keyboard_KeyPressReader_TAB 9L
#undef keyboard_KeyPressReader_Q_MAYUS
#define keyboard_KeyPressReader_Q_MAYUS 81L
#undef keyboard_KeyPressReader_Q_MINUS
#define keyboard_KeyPressReader_Q_MINUS 113L
/*
 * Class:     keyboard_KeyPressReader
 * Method:    getKey
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_keyboard_KeyPressReader_getKey
  (JNIEnv *, jclass);

/*
 * Class:     keyboard_KeyPressReader
 * Method:    getKeyTimeout
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_keyboard_KeyPressReader_getKeyTimeout
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
