/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KeyPressReader */

#ifndef _Included_KeyPressReader
#define _Included_KeyPressReader
#ifdef __cplusplus
extern "C" {
#endif
#undef KeyPressReader_ARROW_UP
#define KeyPressReader_ARROW_UP 1001L
#undef KeyPressReader_ARROW_DOWN
#define KeyPressReader_ARROW_DOWN 1002L
#undef KeyPressReader_ARROW_LEFT
#define KeyPressReader_ARROW_LEFT 1003L
#undef KeyPressReader_ARROW_RIGHT
#define KeyPressReader_ARROW_RIGHT 1004L
#undef KeyPressReader_BACKSPACE
#define KeyPressReader_BACKSPACE 127L
#undef KeyPressReader_INTRO
#define KeyPressReader_INTRO 10L
#undef KeyPressReader_TAB
#define KeyPressReader_TAB 9L
/*
 * Class:     KeyPressReader
 * Method:    getKey
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_KeyPressReader_getKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
